### ISSUE TITLE
非常棒

### ISSUE THREAD

**Issue by kalvinC** [ye11ow/http2-explained-chinese#1]
非常棒！作为一名读者，能否在md前面加一个chapter1_background.md,方便大家阅读！……^_^

**Comment by benluo** [comment]
我私自通知了原作者。

-------- Forwarded Message --------
Subject:    Re: [http2-explained] http2: more refreshed (0826b89)
Date:   Tue, 19 May 2015 23:51:21 -0700

**Comment by ye11ow** [comment]
@kalvinC 实际上我是发布在Gitbook里面的，不过确实也该在文件名上做个index比较好，谢谢建议～

**Comment by ye11ow** [comment]
@benluo 现在虽然是翻译完了，，但是质量很烂，，所以我都没通知他。。还是谢谢你了，哈哈哈

**Comment by benluo** [comment]
早发布，早更正
2015年5月20日 上午7:12于 "Calvin Zhang" notifications@github.com写道：

**Comment by ye11ow** [comment]
Fixed in 79465146a0526da1ffa78cc342c20407bbdbfdd1
